name: Bug Report
description: File a bug report!
title: "(Bug): "
labels: ["bug"]
body:
- type: input
  attributes:
    label: Browser
    description: Which browser are you using?
    placeholder: "Example: Google Chrome"
  validations:
    required: true
- type: input
  attributes:
    label: Browser Version
    description: Which browser version are you using?
    placeholder: "Example: Chromium v95"
  validations:
    required: true
- type: dropdown
  attributes:
    label: "Extension or Userscript?"
    options: 
      - Extension
      - Userscript
  validations:
    required: true
- type: input
  attributes:
    label: Extension/Userscript Version
    description: Which extension/userscript version are you using?
    placeholder: "Example: Version 0.0.0.1"
  validations:
    required: true
- type: textarea
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true