name: Assign issue/pull to the commenter

on:
  issue_comment:
    types: created
    
jobs:
  assign:
    runs-on: ubuntu-latest
    if: |
      github.event.comment.body == '/assignme'
    steps:
      - name: Assigning to commentor
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees":["${{ github.event.comment.user.login }}"]}'
